### PR TITLE
Laravel 10 support

### PR DESCRIPTION
**Pull request by stefblokdijk**

### CODE REVIEW

**Comment by xavierdemaillard** [comment]
Hi !
I'm glad to see that you planned Laravel 10 support !
Did you plan a new version soon ?

**Comment by stefblokdijk** [comment]
@michaelklopf could you release this version?

**Review by michaelklopf — APPROVED** [review]

**Comment by michaelklopf** [comment]
Sorry, I forgot the 10 support. Weird that I didn't see a notification prior of your comment. Done and tagged.

**Comment by xavierdemaillard** [comment]
@michaelklopf Thank you for merge !
@stefblokdijk Thank you fot the PR, perfect timing for our project ;-)

**Pull request merged**
